server:
  port: 8891

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo_permission?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    timeout: 6000

# mybatis配置
#########################
mybatis:
  mapperLocations:  classpath*:mappers/*Mapper.xml
  typeAliasesPackage:  com.tianma.sso.model
  typeHandlersPackage: com.tianma.sso.dao.mybatis.typehandler
  configuration:
    cacheEnabled: true
    # 使用自带mybatis 打印日志不会输出在日志中
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
